### ISSUE TITLE
Support for non integer/fractional blur sizes?

### ISSUE THREAD

**Issue by virtualritz** [awxkee/libblur#3]
First of all, this crate looks great. I especially like that is has support for `u16`/`f32`,

For my use case, I need non integer blur sizes, including even ones. The best I could come up with for larger sizes is to do a blur with radius and radius+1 and linearly blend between those two by the decimal part of the size.

Are `f32` widths planned?

**Comment by awxkee** [comment]
Hi, thanks for your interest in this repository!

Based on your question I'd consider you're asking about pure gaussian blur, correct me if I wrong, because only it restricted to odd kernel sizes.

At first, kernel size is not the same as radius, kernel size in the very base case when you want to blur by radius, is defined as `kernel_size = 2 * radius + 1` what is correct and makes convolution kernel always odd.

Even kernel sizes is not implemented by a reason: convolution kernel will be unbalanced ( have no obvious center ) and this makes the operation is not really mathematically defined. This is acceptable only in narrow cases, when you want to interpolate to a new center, in operations such as _scaling_. Convolution in even kernels not implemented ( because it actually not defined ) in OpenCV also, and I'm not really sure it worth to invent from scratch this operation here.

For fractional blur sizes you `sigma` that controls flattening level.

As for fractional image widths I'm never working with such images so actually it won't benefit any of my projects, therefore there are no such plans.

**Comment by virtualritz** [comment]
Thank you for the quick answer?

How do I express a Guassian blur with e.g. a radius of `1.3` pixels using `sigma`?

**Comment by virtualritz** [comment]
For context: I'm working on a VFX compositing software in Rust and currently I use mostly OpenImageIO (OIIO) through my WIP [`openimageio`](https://github.com/phyrondev/openimageio) Rust wrapper as a backend.

But `libblur` is much faster for blurring so I'm looking into using it instead for those cases. To give you an idea [here are the OIIO docs for the `convolve()` method](
https://openimageio.readthedocs.io/en/v3.0.1.0/imagebufalgo.html#_CPPv4N4OIIO12ImageBufAlgo8convolveERK8ImageBufRK8ImageBufb3ROIi).

OIIO uses kernel images, i.e. the `make_kernel()` call you see in the example code actually generates a resp. image that is then used as a LUT for the convolution. The code will indeed always generate images with odd dimensions. The resp. pixel values then simulate a fractional (pixel) kernel size.

**Comment by awxkee** [comment]
> How do I express a Guassian blur with e.g. a radius of `1.3` pixels using `sigma`?

Basic optimal sigma calculation is:

```rust
pub fn get_optimal_sigma(radius: f32) -> f32 {
    0.3f32 * (radius - 1f32) + 0.8f32
}
```

There is no _one time and for all_ defined method how to calculate `sigma`, you may express it in any function you like.
See [here](https://en.wikipedia.org/wiki/Gaussian_function) what sigma means.



> For context: I'm working on a VFX compositing software in Rust and currently I use mostly OpenImageIO (OIIO) through my WIP [`openimageio`](https://github.com/phyrondev/openimageio) Rust wrapper as a backend.
> 
> But `libblur` is much faster for blurring so I'm looking into using it instead for those cases. To give you an idea [here are the OIIO docs for the `convolve()` method](https://openimageio.readthedocs.io/en/v3.0.1.0/imagebufalgo.html#_CPPv4N4OIIO12ImageBufAlgo8convolveERK8ImageBufRK8ImageBufb3ROIi).
> 
> OIIO uses kernel images, i.e. the `make_kernel()` call you see in the example code actually generates a resp. image that is then used as a LUT for the convolution. The code will indeed always generate images with odd dimensions. The resp. pixel values then simulate a fractional (pixel) kernel size.

You could almost directly bound those API's to libblur's API's by using `filter_2d_rgba_fft`/`filter_2d_rgba`/`filter_1d_rgba_exact` etc.
It should be possible to generate your gaussian 2D kernel by OIIO, solve it using SVD ( gaussian kernel is always separable ), normalize values if they are not, and perform 1d separable convolution by `filter_1d_rgba_exact`/`filter_1d_rgb_exact`/`filter_1d_rgb_approx` and others. Results should be the same except the fact that fractional images are not supported. SVD with linear algebra is unavoidable here if you wish to try this, because attempt to perform gaussian blur using 2D FFT or 2D naive convolution is incredible slow and senseless.

**Comment by awxkee** [comment]
> The `adaptive_blur_impl.rs` seems to go into that direction but the traits are all private.

This is different thing, check ImageMagick documentation what is it considered to be.

> The only limitation is that OIIO supports unlimited number of channels and libblur only supports one, three or four.
> Having more than four channels (or even two) is common in VFX compositing work. I will probably have to do chunking on my side for now to support this.

Deinterleave channels, blur them separately as planar images, and interleave back. This is might be surprising, but actually in many cases this is the fastest method overall, especially for large radii.



> Why not define those as a trait over `T` (the channel type) and then implement trait for the optimized specializations for those types?
> I mean that would make the API surface a lot smaller w/o loosing clarity. You would just have a `GaussianBlur` trait definining`gaussian_blur::<T>(...)`, a `BoxBlur` trait defining `box_blur::<T>(...)`, etc. and those would be implemented for those channel types you support.

This is because planar images convolution, RGB, RGBA all combination were implemented for x86 and NEON and general method by hands with different strategies on different hardware. This is simple to do so when there are no tons of SIMD in many variants for different platform and cases.

**Comment by virtualritz** [comment]
> > The `adaptive_blur_impl.rs` seems to go into that direction but the traits are all private.
> 
> This is different thing, check ImageMagick documentation what is it considered to be.

Yes, I understand. My comment was regarding the implementation approach you chose there, behind the scenes. :grin:.

> Deinterleave channels, blur them separately as planar images, and interleave back. This is might be surprising, but actually in many cases this is the fastest method overall, especially for large radii.

That was my plan for now. OIIO has fast channel shuffling implemented so this is very easy to do.
