### ISSUE TITLE
`stack_blur_u16()` is missing?

### ISSUE THREAD

**Issue by virtualritz** [awxkee/libblur#8]
Is this intentional or an oversight? :grin:

**Comment by awxkee** [comment]
It was intentional.
I was quite naive when I added `fast_gaussian_u16`, hoping it would "just work."
After that I discovered that Gaussian approximations suffer from numerical instability. They are numerically stable only for `f32`, because in most cases `f32` images are normalized. Even when dealing with HDR, the values are not significantly higher than `1.0f32`. 
Almost all implementations of Gaussian approximation on the internet either have low accuracy, or are fast regardless of accuracy, or are numerically unstable for large radii, or have all the issues at the same time. It took some time to overcome these issues for the `u8` images.
`fast_gaussian_u16` now does accurate blur being limited by radius size and at least twice as slow for large radii, while radius is still limited.
I could add `stack_blur_u16` as well, but this would also require making a decision between accuracy, radius limitations, and speed.
